// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserStatistics.Repository;

#nullable disable

namespace UserStatistics.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220717132121_NewProperty")]
    partial class NewProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserStatistics.Entities.Models.Statistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountSignIn")
                        .HasColumnType("int");

                    b.Property<string>("Persentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserStatistics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edae53e4-936c-4e69-aa06-0366cd58f429"),
                            CountSignIn = 12,
                            UserId = new Guid("0627d950-2d3f-421e-be7c-8bf5ad53a7c4")
                        },
                        new
                        {
                            Id = new Guid("ec2c642a-143b-475e-81a2-8198cc090859"),
                            CountSignIn = 8,
                            UserId = new Guid("94a4c1d0-de86-4b47-946e-76c824b9ea71")
                        },
                        new
                        {
                            Id = new Guid("2e71572f-d8a1-44d0-8410-88f108dca28a"),
                            CountSignIn = 2,
                            UserId = new Guid("c22384cf-499e-49f5-ae69-1bbb73e31753")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
