// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserStatistics.Repository;

#nullable disable

namespace UserStatistics.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220707120019_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserStatistics.Entities.Models.Statistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountSignIn")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserStatistics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ef53d72-d4b5-4aeb-a45c-09a45dbf8845"),
                            CountSignIn = 12,
                            UserId = new Guid("645700e9-d10b-4d78-a42b-a6a2816b1d5c")
                        },
                        new
                        {
                            Id = new Guid("e26caf7d-5d9a-4309-849d-4708ed194414"),
                            CountSignIn = 8,
                            UserId = new Guid("4964c711-a20e-4625-9b47-8e2333e9b82a")
                        },
                        new
                        {
                            Id = new Guid("885903ae-1c12-48dc-9b0a-c697e41a9313"),
                            CountSignIn = 2,
                            UserId = new Guid("1e99184f-a135-4f24-a617-31ff6026cb84")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
