// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserStatistics.Repository;

#nullable disable

namespace UserStatistics.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220717183127_PercantageValueInt")]
    partial class PercantageValueInt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserStatistics.Entities.Models.Statistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountSignIn")
                        .HasColumnType("int");

                    b.Property<int>("Persentage")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserStatistics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5a67a4c-c788-4b1b-ac4a-485b23e9c7b9"),
                            CountSignIn = 12,
                            Persentage = 0,
                            UserId = new Guid("31c4b5c9-8420-4705-acef-ec5723bc97e1")
                        },
                        new
                        {
                            Id = new Guid("9417ecd5-ed64-45c1-b94b-221670dd3e24"),
                            CountSignIn = 8,
                            Persentage = 0,
                            UserId = new Guid("b2b17a85-0b06-4ef3-9f73-2b3f5cb7108a")
                        },
                        new
                        {
                            Id = new Guid("4863267b-cdef-43ca-9552-638d5151d7e0"),
                            CountSignIn = 2,
                            Persentage = 0,
                            UserId = new Guid("b3897378-089b-4d28-9867-1caaef236ca2")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
